from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from datetime import datetime
import io

router = APIRouter(prefix="/report", tags=["Security Report"])

class ReportRequest(BaseModel):
    scan_type: str  # "url", "email", "visual"
    target: str     # The URL/Email/Filename scanned
    result: str     # "legitimate", "suspicious", "phishing"
    confidence: float
    explanation: str

@router.post("/generate")
async def generate_pdf_report(payload: ReportRequest):
    """
    Generate a professional PDF security certificate.
    Uses reportlab to create a branded document.
    """
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas
    from reportlab.lib.colors import HexColor
    
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    
    # --- HEADER ---
    c.setFillColor(HexColor("#0f172a"))
    c.rect(0, height - 120, width, 120, fill=True, stroke=False)
    
    c.setFillColor(HexColor("#22d3ee"))
    c.setFont("Helvetica-Bold", 28)
    c.drawString(50, height - 70, "CYBERBUDDY X")
    
    c.setFillColor(HexColor("#94a3b8"))
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 95, "AI-Powered Security Analysis Report")
    
    # --- BODY ---
    c.setFillColor(HexColor("#0f172a"))
    
    # Scan Info
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 160, f"Scan Type: {payload.scan_type.upper()}")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 185, f"Target: {payload.target[:60]}...")
    c.drawString(50, height - 210, f"Scanned At: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}")
    
    # Result Box
    result_color = "#10b981" if payload.result == "legitimate" else "#f43f5e"
    c.setFillColor(HexColor(result_color))
    c.roundRect(50, height - 320, 250, 80, 10, fill=True, stroke=False)
    
    c.setFillColor(HexColor("#ffffff"))
    c.setFont("Helvetica-Bold", 24)
    c.drawString(70, height - 275, payload.result.upper())
    
    c.setFont("Helvetica", 12)
    c.drawString(70, height - 300, f"Confidence: {payload.confidence}%")
    
    # Explanation
    c.setFillColor(HexColor("#0f172a"))
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 360, "AI Analysis:")
    
    c.setFont("Helvetica", 11)
    # Word wrap explanation
    explanation_lines = [payload.explanation[i:i+80] for i in range(0, len(payload.explanation), 80)]
    y_pos = height - 385
    for line in explanation_lines[:5]:
        c.drawString(50, y_pos, line)
        y_pos -= 18
    
    # --- FOOTER ---
    c.setFillColor(HexColor("#64748b"))
    c.setFont("Helvetica", 9)
    c.drawString(50, 50, "This report was generated by CyberBuddy X. For informational purposes only.")
    c.drawString(50, 35, f"Report ID: CB-{datetime.now().strftime('%Y%m%d%H%M%S')}")
    
    c.save()
    buffer.seek(0)
    
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=CyberBuddy_Report_{datetime.now().strftime('%Y%m%d')}.pdf"}
    )
